[project]
name = "BoolODE"
version = "0.1"
requires-python = "==3.7"

[build-system]
requires = ["setuptools<=59.8.0"]
build-backend = "setuptools.build_meta"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
